// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReq struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type ReadReq struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReq) Reset()         { *m = ReadReq{} }
func (m *ReadReq) String() string { return proto.CompactTextString(m) }
func (*ReadReq) ProtoMessage()    {}
func (*ReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq.Unmarshal(m, b)
}
func (m *ReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq.Marshal(b, m, deterministic)
}
func (m *ReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq.Merge(m, src)
}
func (m *ReadReq) XXX_Size() int {
	return xxx_messageInfo_ReadReq.Size(m)
}
func (m *ReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq proto.InternalMessageInfo

func (m *ReadReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReadReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateReq struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	File                 *File    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UpdateReq) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type DeleteReq struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeleteReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FileRes struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRes) Reset()         { *m = FileRes{} }
func (m *FileRes) String() string { return proto.CompactTextString(m) }
func (*FileRes) ProtoMessage()    {}
func (*FileRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *FileRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRes.Unmarshal(m, b)
}
func (m *FileRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRes.Marshal(b, m, deterministic)
}
func (m *FileRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRes.Merge(m, src)
}
func (m *FileRes) XXX_Size() int {
	return xxx_messageInfo_FileRes.Size(m)
}
func (m *FileRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRes.DiscardUnknown(m)
}

var xxx_messageInfo_FileRes proto.InternalMessageInfo

func (m *FileRes) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type BoolRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolRes) Reset()         { *m = BoolRes{} }
func (m *BoolRes) String() string { return proto.CompactTextString(m) }
func (*BoolRes) ProtoMessage()    {}
func (*BoolRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *BoolRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolRes.Unmarshal(m, b)
}
func (m *BoolRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolRes.Marshal(b, m, deterministic)
}
func (m *BoolRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolRes.Merge(m, src)
}
func (m *BoolRes) XXX_Size() int {
	return xxx_messageInfo_BoolRes.Size(m)
}
func (m *BoolRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolRes.DiscardUnknown(m)
}

var xxx_messageInfo_BoolRes proto.InternalMessageInfo

func (m *BoolRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListFilesReq struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesReq) Reset()         { *m = ListFilesReq{} }
func (m *ListFilesReq) String() string { return proto.CompactTextString(m) }
func (*ListFilesReq) ProtoMessage()    {}
func (*ListFilesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ListFilesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesReq.Unmarshal(m, b)
}
func (m *ListFilesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesReq.Marshal(b, m, deterministic)
}
func (m *ListFilesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesReq.Merge(m, src)
}
func (m *ListFilesReq) XXX_Size() int {
	return xxx_messageInfo_ListFilesReq.Size(m)
}
func (m *ListFilesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesReq proto.InternalMessageInfo

func (m *ListFilesReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ListFilesRes struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesRes) Reset()         { *m = ListFilesRes{} }
func (m *ListFilesRes) String() string { return proto.CompactTextString(m) }
func (*ListFilesRes) ProtoMessage()    {}
func (*ListFilesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ListFilesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesRes.Unmarshal(m, b)
}
func (m *ListFilesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesRes.Marshal(b, m, deterministic)
}
func (m *ListFilesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesRes.Merge(m, src)
}
func (m *ListFilesRes) XXX_Size() int {
	return xxx_messageInfo_ListFilesRes.Size(m)
}
func (m *ListFilesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesRes proto.InternalMessageInfo

func (m *ListFilesRes) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	IsFolder             bool     `protobuf:"varint,5,opt,name=isFolder,proto3" json:"isFolder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetIsFolder() bool {
	if m != nil {
		return m.IsFolder
	}
	return false
}

type Owner struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Owner) Reset()         { *m = Owner{} }
func (m *Owner) String() string { return proto.CompactTextString(m) }
func (*Owner) ProtoMessage()    {}
func (*Owner) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *Owner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Owner.Unmarshal(m, b)
}
func (m *Owner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Owner.Marshal(b, m, deterministic)
}
func (m *Owner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Owner.Merge(m, src)
}
func (m *Owner) XXX_Size() int {
	return xxx_messageInfo_Owner.Size(m)
}
func (m *Owner) XXX_DiscardUnknown() {
	xxx_messageInfo_Owner.DiscardUnknown(m)
}

var xxx_messageInfo_Owner proto.InternalMessageInfo

func (m *Owner) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddOwnerReq struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerToAdd           string   `protobuf:"bytes,2,opt,name=ownerToAdd,proto3" json:"ownerToAdd,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOwnerReq) Reset()         { *m = AddOwnerReq{} }
func (m *AddOwnerReq) String() string { return proto.CompactTextString(m) }
func (*AddOwnerReq) ProtoMessage()    {}
func (*AddOwnerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *AddOwnerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOwnerReq.Unmarshal(m, b)
}
func (m *AddOwnerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOwnerReq.Marshal(b, m, deterministic)
}
func (m *AddOwnerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOwnerReq.Merge(m, src)
}
func (m *AddOwnerReq) XXX_Size() int {
	return xxx_messageInfo_AddOwnerReq.Size(m)
}
func (m *AddOwnerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOwnerReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddOwnerReq proto.InternalMessageInfo

func (m *AddOwnerReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AddOwnerReq) GetOwnerToAdd() string {
	if m != nil {
		return m.OwnerToAdd
	}
	return ""
}

func (m *AddOwnerReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateReq)(nil), "proto.CreateReq")
	proto.RegisterType((*ReadReq)(nil), "proto.ReadReq")
	proto.RegisterType((*UpdateReq)(nil), "proto.UpdateReq")
	proto.RegisterType((*DeleteReq)(nil), "proto.DeleteReq")
	proto.RegisterType((*FileRes)(nil), "proto.FileRes")
	proto.RegisterType((*BoolRes)(nil), "proto.BoolRes")
	proto.RegisterType((*ListFilesReq)(nil), "proto.ListFilesReq")
	proto.RegisterType((*ListFilesRes)(nil), "proto.ListFilesRes")
	proto.RegisterType((*File)(nil), "proto.File")
	proto.RegisterType((*Owner)(nil), "proto.Owner")
	proto.RegisterType((*AddOwnerReq)(nil), "proto.AddOwnerReq")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5f, 0x4b, 0xfb, 0x30,
	0x14, 0xa5, 0x5d, 0xbb, 0xae, 0x77, 0xbf, 0xdf, 0x90, 0x28, 0x58, 0xf6, 0xe0, 0x9f, 0x28, 0x22,
	0x43, 0x26, 0x9b, 0xf8, 0x01, 0x36, 0x65, 0x4f, 0x82, 0x50, 0x15, 0x9f, 0xeb, 0x72, 0xc5, 0x40,
	0x5d, 0x6a, 0x53, 0xf5, 0x63, 0xfb, 0x15, 0x24, 0x49, 0x1b, 0xeb, 0x6c, 0xf5, 0xa9, 0xb9, 0xe7,
	0x9e, 0xdc, 0x93, 0x7b, 0x7a, 0xe0, 0xbf, 0xc4, 0xfc, 0x8d, 0x2f, 0x71, 0x9c, 0xe5, 0xa2, 0x10,
	0xc4, 0xd7, 0x1f, 0x7a, 0x02, 0xe1, 0x45, 0x8e, 0x49, 0x81, 0x31, 0xbe, 0x90, 0x5d, 0xf0, 0x1e,
	0x79, 0x8a, 0x91, 0xb3, 0xe7, 0x1c, 0xf7, 0xa7, 0x7d, 0xc3, 0x1c, 0x2f, 0x78, 0x8a, 0xb1, 0x6e,
	0xd0, 0x53, 0x08, 0x62, 0x4c, 0x98, 0xe2, 0x6e, 0x81, 0x2f, 0xde, 0x57, 0x98, 0x6b, 0x72, 0x18,
	0x9b, 0x82, 0x0c, 0xc0, 0xe5, 0x2c, 0x72, 0x35, 0xe4, 0x72, 0x46, 0xe7, 0x10, 0xde, 0x65, 0xac,
	0x1c, 0xdf, 0x7c, 0xa5, 0x12, 0x75, 0xdb, 0x44, 0x27, 0x10, 0x5e, 0x62, 0x8a, 0xbf, 0xcd, 0x58,
	0x97, 0x1d, 0x41, 0xa0, 0x07, 0xa0, 0xfc, 0x7b, 0xa7, 0x03, 0x08, 0xe6, 0x42, 0xa4, 0x8a, 0x1b,
	0x41, 0x20, 0x5f, 0x97, 0x4b, 0x94, 0x52, 0xd3, 0x7b, 0x71, 0x55, 0xd2, 0x43, 0xf8, 0x77, 0xc5,
	0x65, 0xa1, 0xae, 0xc9, 0xd6, 0x67, 0xd0, 0xc9, 0x37, 0x96, 0x24, 0xfb, 0xe0, 0x2b, 0x09, 0x35,
	0xad, 0xb3, 0x2e, 0x6e, 0x3a, 0x34, 0x03, 0x4f, 0x95, 0xe5, 0x06, 0x4e, 0xb5, 0xc1, 0x97, 0x80,
	0x5b, 0xdf, 0x93, 0x80, 0x97, 0x25, 0xc5, 0x53, 0xd4, 0xd1, 0xa0, 0x3e, 0x2b, 0x6c, 0x95, 0x3c,
	0x63, 0xe4, 0x19, 0x4c, 0x9d, 0xc9, 0x10, 0x7a, 0x5c, 0x2e, 0x44, 0xca, 0x30, 0x8f, 0x7c, 0xbd,
	0x89, 0xad, 0xe9, 0x36, 0xf8, 0xd7, 0x35, 0xd3, 0xac, 0x24, 0xbd, 0x87, 0xfe, 0x8c, 0x31, 0xdd,
	0x6b, 0x77, 0x7a, 0x07, 0x40, 0x1f, 0x6e, 0xc5, 0x8c, 0x55, 0x8e, 0xd7, 0x90, 0xa6, 0x17, 0x4e,
	0x3f, 0x1c, 0x80, 0x19, 0x63, 0x37, 0x26, 0x7f, 0x64, 0x04, 0x5d, 0x13, 0x39, 0xb2, 0x51, 0x1a,
	0x62, 0x13, 0x38, 0x1c, 0xd4, 0x2d, 0x42, 0x49, 0x8e, 0xc0, 0x53, 0x81, 0x23, 0x15, 0x5e, 0xa6,
	0xef, 0x07, 0x6f, 0x04, 0x5d, 0x93, 0x33, 0x3b, 0xd3, 0xc6, 0xae, 0x89, 0x6b, 0xf2, 0x64, 0xb9,
	0x36, 0x5e, 0x96, 0x5b, 0x25, 0xe2, 0x1c, 0x42, 0xfb, 0x47, 0xc9, 0x66, 0xd9, 0xac, 0x27, 0x61,
	0xd8, 0x00, 0xca, 0x87, 0xae, 0xc6, 0xce, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x36, 0x28,
	0x49, 0x74, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*FileRes, error)
	Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*FileRes, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*FileRes, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*BoolRes, error)
	ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesRes, error)
}

type addServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddServiceClient(cc *grpc.ClientConn) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*FileRes, error) {
	out := new(FileRes)
	err := c.cc.Invoke(ctx, "/proto.AddService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*FileRes, error) {
	out := new(FileRes)
	err := c.cc.Invoke(ctx, "/proto.AddService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*FileRes, error) {
	out := new(FileRes)
	err := c.cc.Invoke(ctx, "/proto.AddService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*BoolRes, error) {
	out := new(BoolRes)
	err := c.cc.Invoke(ctx, "/proto.AddService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesRes, error) {
	out := new(ListFilesRes)
	err := c.cc.Invoke(ctx, "/proto.AddService/ListFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	Create(context.Context, *CreateReq) (*FileRes, error)
	Read(context.Context, *ReadReq) (*FileRes, error)
	Update(context.Context, *UpdateReq) (*FileRes, error)
	Delete(context.Context, *DeleteReq) (*BoolRes, error)
	ListFiles(context.Context, *ListFilesReq) (*ListFilesRes, error)
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) Create(ctx context.Context, req *CreateReq) (*FileRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAddServiceServer) Read(ctx context.Context, req *ReadReq) (*FileRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedAddServiceServer) Update(ctx context.Context, req *UpdateReq) (*FileRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAddServiceServer) Delete(ctx context.Context, req *DeleteReq) (*BoolRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedAddServiceServer) ListFiles(ctx context.Context, req *ListFilesReq) (*ListFilesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Read(ctx, req.(*ReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).ListFiles(ctx, req.(*ListFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AddService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AddService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AddService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AddService_Delete_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _AddService_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
